[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
unikron = "2bgpPzHUWu9jRAMUcF2Kex4dKti6U554hkhpkBi4EpHK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx ts-mocha --project ./tsconfig.json --timeout 1000000 tests/**/*.ts"
